"""add transaction number

Revision ID: 175e60615eb3
Revises: d2fea1664aab
Create Date: 2025-01-06 21:36:50.758577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '175e60615eb3'
down_revision = 'd2fea1664aab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_number', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['transaction_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('transaction_number')

    # ### end Alembic commands ###
